---
- name: Deploy Flask app using Ansible
  hosts: webservers
  become: yes

  tasks:
    - name: Ensure required packages are installed
      apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Install Flask globally using pip3
      pip:
        name: flask
        executable: pip3

    - name: Ensure app directory exists
      file:
        path: /home/praveen_a/app
        state: directory
        owner: praveen_a
        group: praveen_a
        mode: '0755'

    - name: Copy application code to server
      copy:
        src: "{{ playbook_dir }}/../"
        dest: /home/praveen_a/app/
        owner: praveen_a
        group: praveen_a
        mode: '0755'

    - name: Kill any existing app.py process
      shell: |
        pkill -f app.py || true

    - name: Start Flask app using nohup
      shell: |
        cd /home/praveen_a/app
        nohup python3 app.py > app.log 2>&1 &
      args:
        executable: /bin/bash

    - name: Verify app.py is running
      shell: pgrep -f app.py
      register: app_status
      failed_when: app_status.rc != 0
      changed_when: false

